name: Rust

on:
  push:
    branches: [ main, development, actions ]
  pull_request:
    branches: [ main, development, actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
          
      - name: Build
        run: cargo build --all --release && strip target/release/rocket_testing && mv target/release/rocket_testing target/release/rocket_testing_amd64
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: |
            target/release/rocket_testing_amd64
            target/release/Rocket.toml
            target/release/resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: |
            target/release/rocket_testing.exe
            target/release/Rocket.toml
            target/release/resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}